spring.application.name=cotizador-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cotizador_db_spring
spring.datasource.username=neuralCode
spring.datasource.password=NeuralCode@Admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger Configuration (rutas por defecto: /swagger-ui.html y /v3/api-docs)
